kind: Secret
ansible_host: ENC[AES256_GCM,data:a7g02IzsSZ5EHe6xngw=,iv:ZWuQ2QBQ6v+kf7KfoV7UzWWDGCVXEqvrJS1fk8Q2JDU=,tag:7jRTbe5g9ydCcT56Ktw2ng==,type:str]
ansible_user: ENC[AES256_GCM,data:QgYhKA==,iv:ZfpEC4kB+e7Fda65NeYq7bu2mqYz68yoHqPORVHsqoQ=,tag:RqosJcuBFZTB9AgCwugtJw==,type:str]
iperf3_client_hostname: ENC[AES256_GCM,data:df8H6PzuUuf5azDMbfJj8MF+,iv:0DV741zLIrmpkyjA8ohTUQhGcSokMg+vGBZvNnkC4ow=,tag:svOiWV7FdPB7Kq6phsyXig==,type:str]
#ENC[AES256_GCM,data:+ebsAp3uto/oQiTvm6RMTzrJSvvFFByF4Axfybbd,iv:37cu5eel5vvN2EjO4FbLeTdVP7uAO3aW7eSlNXaPKqo=,tag:pulWpB3fRvbZV+XVPubBqA==,type:comment]
amneziawg_interfaces_host:
    awg1:
        #ENC[AES256_GCM,data:oNwk8KJDrJonNkufRmFN,iv:AP+BLu7nKQlNjUqAYxe0HT4FM7Ns7nD0IHGx14v16Nc=,tag:Z1z551qpoFhsYc0hRfEBjg==,type:comment]
        mode: ENC[AES256_GCM,data:XzJLsbod,iv:GRcT1HG7zD9IApdI6zT5WHfui9b34m0OWwAESkZt04A=,tag:CDXwpmZDjhETA6MqLyo0qw==,type:str]
        public_key: ENC[AES256_GCM,data:sUmqQfwNlAArHyZ7laExzBLaSDSfNyH7btaBg6FYVHaQbErkaf0Css6W43I=,iv:B2ig+ggveYZqe7SosV9GfxngdsVI1owrfA4xUseNZW4=,tag:W8BmPF6ezUuiDs6Z0dTl2w==,type:str]
        private_key: ENC[AES256_GCM,data:o8+qjErkrlPsTtrVJPbtONisFH5b8C7hNy3b26lz0WZnLoMD2mXQEPdaeMY=,iv:FBe/Cnc4YC9xIxK4lp2XYL0i5OGzeCl9/fnCHzl+WgY=,tag:2ZFFFZjMPMFIczmfyh/UBg==,type:str]
        remote_preshared_key: ENC[AES256_GCM,data:7VPmFHZRO8Fg6cNmZcmX3t6QbG+jXBalVgpRrp/c2m4hM6dwZtdfrLqYL+I=,iv:YCdTTVqsTNyxvhLri20VA+ojOtx3KG2NhhhQiPbriSM=,tag:/nihwrS3kFkk0+Y+/fgXVw==,type:str]
        mtu: ENC[AES256_GCM,data:O2YgtA==,iv:dOCcEaNuy5I+77t9IzZjvZWIFCvP22zJE1HclT/cYBg=,tag:lqyh5Zpfgas+tfKelmkQHQ==,type:int]
        port: ENC[AES256_GCM,data:S52lLLE=,iv:zs/9+vFt0U+2n/qd1hGvCNqSKdvkPScAvWsWOjDy0lA=,tag:nOlSSBcYwbIjTsfg8NWJOQ==,type:int]
        #ENC[AES256_GCM,data:JsbSEBPUKCYOSRtIm2FoKJhN32GLAQ==,iv:4TXCGD+uFPSQIPrG3It4N5XfpAFp+06pa/v1PIjgsnc=,tag:3uDMNlWUwVMrrvTayfhi8g==,type:comment]
        address_v4: ENC[AES256_GCM,data:YF6SiNVSyCW8b7g=,iv:86aQGJvR0nud+MNoIq9Ytttrux1/P2hauLmntCLpziw=,tag:yeu6F11JVT5KSTpfN4yaQg==,type:str]
        subnet_v4: ENC[AES256_GCM,data:Ya8=,iv:ap2ceVt5S4zXRfo+asdBDBW6XGS0kAIvzevk2jAHPk0=,tag:A7l6es8ZNm84WKQTPOUWbg==,type:int]
        clients_subnet_v4: ENC[AES256_GCM,data:pVY=,iv:l28gLuNwVRFWMCJMP1x9xRpcldSd8WGuS8ZXjXOSnUM=,tag:Ci+4nTLlRiUbkBUMdyhpHg==,type:int]
        address_v6: ENC[AES256_GCM,data:zpnrVGR+km/Xere68S5dfFHqZg==,iv:VMjwABY8tsV8hcMebabpeyCVVWGd24a9SFcRzzcgAIc=,tag:FrHe+GKGTapnLG4Lv7HsuQ==,type:str]
        subnet_v6: ENC[AES256_GCM,data:Bg6h,iv:B7Gw+LKryfy6GGgAcRHJ5JsCxBorR3wBRbuvHJgIcqw=,tag:4FGgGGKmtQmM5FaiiflcnA==,type:int]
        clients_subnet_v6: ENC[AES256_GCM,data:gP0H,iv:qPCRBaJ6/Ejxe1xevjBZ8C5837QTVUApLLkc/N43JX0=,tag:WFlMiQNyEZEqQABmR0X1ew==,type:int]
        #ENC[AES256_GCM,data:ooO+bB6HJCq+PvoOYN8M9UqG2DB4,iv:99CGVRBkSCMvOPp43u8XQILNA8aocerydphTPvThrRY=,tag:QNaxt5ksKaPjz+XVetPNvQ==,type:comment]
        remote_endpoint: ENC[AES256_GCM,data:LXZe9u0CXfYhPtXA4Djswb5rAbXjZTQ2,iv:OkoLZxrJqHdfWKJnQ8mBdfWrTCa68ijFrMABP9MHRDc=,tag:E1/g0/d5J0mPLqaPbYGYtg==,type:str]
        remote_public_key: ENC[AES256_GCM,data:vQptbjsRaKNCaDoMzPrTbMfid6WzEwYX5/QFIOjUMkQyrVPl2JwihF9aetc=,iv:OVPGD+aTxOOoFKfYkg8toLdstK54uCYR7p4fQgJOMqk=,tag:bmGnzpjyb+VyXqwjNMmL8g==,type:str]
        remote_allowed_ips: ENC[AES256_GCM,data:IogiR8U4MAAgfkc/MaK7,iv:SrdTz0ofS8Smuvqyvmfaai1N7+CqReKCw/IV+HDIf/8=,tag:90P5fbJY5JjDybxG1KzqPg==,type:str]
        routing_table: ENC[AES256_GCM,data:yz9SNg==,iv:LwT+d0bzxeMt0Qj+LRlKDmS+RLOO31MseX//kx7uQMw=,tag:gsvaEpK+dJHj8CmHnoScdw==,type:str]
        routing_table_name: ENC[AES256_GCM,data:3UX8iSNqHQUwTw==,iv:ez3fbc0gUNC8Qn4HCfNpM95lcVRcPPl9sMoi6NHtQk8=,tag:vinUXmcOlU+JlwOoEzHLlA==,type:str]
        routing_rules:
            - from: ENC[AES256_GCM,data:M1IHF/Xi9KlTVQc=,iv:s7CpuPMsunjC0L8jmgqI6x3Sf4+RxYqOuxlQLrLe0VQ=,tag:OV7qq8T87SYrmjUEHprIgQ==,type:str]
              table: ENC[AES256_GCM,data:6DFUWA==,iv:DMAZp3eXxGq3dbZ74842leBw4gSfOu0Ejw0r1SLzv9c=,tag:Z9ZW72UhiB0s+kkyTZ7zyg==,type:int]
        #ENC[AES256_GCM,data:5eEoFphh9gi5xZO72iSZuND9O3qkRDWdUAOvTvGNbH1V7U3+1mezJNob7E3mZI4ztJSE,iv:yU5cN5KTZbeYlAivA3c9iiDv+89mrztU6Fz2wO+joVs=,tag:vjtLUgLOLpQqP7Y85+qu6g==,type:comment]
        jc: ENC[AES256_GCM,data:eA==,iv:4Q9+KGTYXTk5ZYLsAHO+tE4vNdf4FfWMslc1ivxsylg=,tag:BfBmwpbnsdN1mRBeyYZGSw==,type:int]
        jmin: ENC[AES256_GCM,data:PIfL,iv:AWLMHBFb+LB2lWf1pqZR2pY9p29S+FFI/2TYZa6rmd0=,tag:txBJT+oJfYQEtSuQBrR6GA==,type:int]
        jmax: ENC[AES256_GCM,data:ZvDewQ==,iv:cuPtR7erg4KGGhpHdOj8F0pWSnsaBaU8+dnd+fVSI9A=,tag:GL/XfBlhgFziFI7uCrjN6A==,type:int]
        s1: ENC[AES256_GCM,data:10s=,iv:bVsGsbYcwQBhlDJAlLB3H9vLfZjumw3RMvvD7s4l6XE=,tag:UxiGVEh0N4/7O5HODCB6iw==,type:int]
        s2: ENC[AES256_GCM,data:N/1t,iv:s+CZNdjuMs9ioCQkTpP81kSf9btwwPVvxpNDx4+LuDM=,tag:zatd92OppQ0EzkZa221c3w==,type:int]
        h1: ENC[AES256_GCM,data:qagr8knZ2zXf,iv:96vxHTj8K1c2Z9dadqkrhL2em7fGj2g1O/LV7cJ/5Pc=,tag:7NTgQEMht6ddk42g6R2B9g==,type:int]
        h2: ENC[AES256_GCM,data:V5YoROqSuUCA,iv:cmoeiSr2DMDxZDh3HYCBt/Fm41EbwDUKHC4nG3ghdEA=,tag:5iMY4/UMoOWo6m/OhaGbyg==,type:int]
        h3: ENC[AES256_GCM,data:q9NJ52wJzQDT,iv:Jcn/WhlARfkflWPSVv3eAW9Za6M6McQhjac/JHBW5Ic=,tag:xiP5IWxKTCAhTKhs/6XGUQ==,type:int]
        h4: ENC[AES256_GCM,data:4mAm00MRNvkg,iv:BQno2rwKKOXEAri9ntzm/k1XnWULjad9j89H8ny9E1Q=,tag:QWbu89EDMXMn/+8q+xEixw==,type:int]
    awg2:
        #ENC[AES256_GCM,data:WeiRGHHWZ9GMgx7uZu15,iv:63lNovcWkjzGS4epHSxUs/ae0gGGqx0v1RjCfSYQe10=,tag:TPh/4rBnxifpuPINgNmOqg==,type:comment]
        mode: ENC[AES256_GCM,data:v7318QIG,iv:nDYsp2tJGUorlU4FtJYUFg5PCbkXVFwl1p+65WOIPVc=,tag:uA4CjQXNQ7ed18kSGHg1BQ==,type:str]
        public_key: ENC[AES256_GCM,data:YIqz71pEZWBiYqHxmMl66yFu6YJLMPtkpZgxQ0FW18lJBzrGOmCgkgLIsHg=,iv:toC44Xu1NNORyIZiDfMV+tw2HJLZ5/iOWzbebtAY4e4=,tag:mAr/4Y+FjRhAcj+VdrVYrA==,type:str]
        private_key: ENC[AES256_GCM,data:yTU7lShaLj/3xBcKwGYNrg7jnllZ6sLv+y35ks5saATnv3twU/3nI09+9X0=,iv:3CiHCbofNBYBdavKGrYNtiNqUY1EZqTB5pfuwJCqe70=,tag:5tKCGOFmhxRE/8q1F5iPGA==,type:str]
        mtu: ENC[AES256_GCM,data:GdmdYQ==,iv:lMhxyrODI6EYX8toeIw4KHNePL00cVM2YrLleAiEx0A=,tag:sSWjAXKSdYRC3Ucwqq/eCA==,type:int]
        #ENC[AES256_GCM,data:IIX7oRYY3weZTBCAFP0nLUXveI8YSw==,iv:xrzvmeHK4+0zdESBxcxQohN/s3n79yEo1G2lgmt8htc=,tag:BuMQD8CpWuY8nZoK+852Cw==,type:comment]
        address_v4: ENC[AES256_GCM,data:MYXcqLKC9TI=,iv:gPI+pv9GBx8tMQSCdAtahsr+FDRXCQKJETCyWQa+qzs=,tag:nm8pXEg/51oGvl3eUBU0eA==,type:str]
        subnet_v4: ENC[AES256_GCM,data:REI=,iv:yVUbCKR7oGIb5z7ZSohvmrm7JUV6rFt5kwaNb3V+d2k=,tag:LX0Qmz9O/KMGThclk+j87Q==,type:int]
        clients_subnet_v4: ENC[AES256_GCM,data:LL8=,iv:O/mzse/duSNkLAKhypU4ac54ksKA2uUOPYKrExDWN4Q=,tag:dSlcnLnGuzsPbDyegubV3A==,type:int]
        address_v6: ENC[AES256_GCM,data:JY5vmR96a9hO6JRDE8xb4fo=,iv:HSmqujLWel31PwOgVoA9Age7wWmEIiCl856l8Y5lOnI=,tag:pLrddCqF7SLYXxGtcbzUyA==,type:str]
        subnet_v6: ENC[AES256_GCM,data:PLQ=,iv:9lBqM2SCqaL30vlaEzU0cWgxrZepEvw8l87KQukSK4w=,tag:7Tlr6s5ujxzQpJJ/7T9msQ==,type:int]
        clients_subnet_v6: ENC[AES256_GCM,data:XwYl,iv:uiMcwLgg+MP9N7GKtiOb4FCPb/VGj1ljidLHPtyUFUM=,tag:Brm9Z2VhDFCq1qhLeYTMig==,type:int]
        #ENC[AES256_GCM,data:tl2nqXWeQVGhUE6ShE5zK7vlne9o,iv:M3L1FfF5/VPegaurZTxoSRu1SKmly5AWSkgUoQzxOeY=,tag:jIXdjGh2P6KXMSBlAr3Crw==,type:comment]
        port: ENC[AES256_GCM,data:sl1H0sQ=,iv:1UIUAhIHnG7j3RpcOU0zqchDEbZq25yftB1kDxf1zFU=,tag:az0eJHnlBqOutnr29sJPfQ==,type:int]
        public_host: ENC[AES256_GCM,data:pn8UrSR9FFkLw18U48YwyQ==,iv:G/9DAiNNWAxcrMvYhKNJH60fFnDnJH+kDda20QkjwzA=,tag:gQQimigT0jcORRA9rGVYYA==,type:str]
        public_interface: ENC[AES256_GCM,data:1F6XzwPP,iv:zMxFhdeJlNwAwgMWYwNUyez1qKoa+xVyP4uK77x7qTc=,tag:T+L+c6Ax7GLl3qv4dyKj2A==,type:str]
        private_interface: ENC[AES256_GCM,data:ahtOjw==,iv:hPIIIbWlqghIniEUPQOKyc1NCxXMlgmnt97h7kuKGwo=,tag:K4zdRMSt7XY9VhzXboV69Q==,type:str]
        #ENC[AES256_GCM,data:KqMJDx32uVHzrosQncijTwtSgRuYQ/aiYhc5vh90bdDtF3uPBp+s9D4xGohxESX42aXh,iv:65nE7/xi6NkrwCUoe5XFNzanzYSy7iFLdZ+qzbKin2A=,tag:ckRUN6Vz5d6jb6N+K+9Qdg==,type:comment]
        jc: ENC[AES256_GCM,data:Ow==,iv:5b+CCkLjh5xH81sjRLChjhVVXL3ALn8C6a3eMuMuWBA=,tag:nW/kNDDCnGzOno61svAv7w==,type:int]
        jmin: ENC[AES256_GCM,data:sM4g,iv:yO8fycWZQTYOtp/K6bELTUIrlXnIIaiO5OwpKrtMRl8=,tag:IiwA2ShNhI1mDtuNspX+xA==,type:int]
        jmax: ENC[AES256_GCM,data:1CMknQ==,iv:00/T1eP/DeASjQVS/DAYnQ/XZITdV1VbbK0r0woVSnU=,tag:9e+U2V/12T3uKDl4nYPKAw==,type:int]
        s1: ENC[AES256_GCM,data:cvo=,iv:axQH2CqOOPkMKERfLdoYIl5hDvWK1It5jp6+18/2wQQ=,tag:bYuCxgb4et4AjC7l4tYmWA==,type:int]
        s2: ENC[AES256_GCM,data:4qs=,iv:Ne7MjhUxVWqcMX+sQs4j+XEBsM1aA7PPLehMU4jMxQY=,tag:UX7EPsG6969e1cZg65zHWA==,type:int]
        h1: ENC[AES256_GCM,data:ld5DlUgckc5B,iv:veSoy9EQHKF3z+djLmH6OuhRKpAwEK/ZxKNxrvXhHf0=,tag:pI9F9mHDFGquMpF+Yv6bjA==,type:int]
        h2: ENC[AES256_GCM,data:WvZtIwN1yiJU,iv:dx5XJGenZAWzyerzGVQAad6ktgvb0aIOkM0pc6/3BS4=,tag:px0BMOUhV+E1o4llmjmxoQ==,type:int]
        h3: ENC[AES256_GCM,data:Kn+7RAI06zY8Pw==,iv:Z4FdHxTtbselqeWFhanZbGEHcpXKaxhEMXoE2padoCk=,tag:lW6UmC2iZDGev1Tts9pBgg==,type:int]
        h4: ENC[AES256_GCM,data:j1j6anBEeJxa,iv:tf6c4lmf9e89wC0IIUX0B8i0XKcMK3d3aO2L5rMH+Z0=,tag:TRdR5vC5L1cKEnRMKFPPjg==,type:int]
        peers:
            - ENC[AES256_GCM,data:OH7Uh6uV,iv:wHyoAPV2mckvxUZGuLdB7PqgWEvFDMhDwABhCUNGbrc=,tag:euyiLT2eSa7A8qXd6pLJzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVoraGdURCs2U1ZjMFY5
            c2pyWFBzS0dWemhPT1pSVk1Cd01xOUZocXk0CnYxeTNqZHVzYk9FNS9MSDFoazUz
            ZkQrczhxWEx4dE5WblIwdG9IWGpKOUUKLS0tIEdEMXZPa1gybStDR1p0dFEyNnpF
            Y284bkQ5Y09yN3pyRDVkWHk4TVFhZk0KsuXMnTcefEaBnZrA2lUIB6Q7Nd/ASndZ
            OufZVVJTOADqMzcmicsz03ozIrTPcYbHE8Q5n2oKIJ6XLenwrcrDFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T16:08:00Z"
    mac: ENC[AES256_GCM,data:A7RzvUvJQikBkyIl4C0rVs6T3pO68xyMrZ4xEUmlCqtyq+Pcxrcj74r8dH4HKe5jzPW5bR4z7Wr5MCuXXfmmr+02OiToFxgeP1szWLUFICqUDT+nnz5dp9xihYdlD/K/CmyDi7sOyB9VLl4Jx6YTGF1gztOuOq4l7iQ5nBBCXFs=,iv:j7WayPe9w+iO91FxM0K8jGgCE/PWuyZrFsuXVkaa4HY=,tag:mvCvuf/lIOMy+9Bvi+Pcyw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
