---
collections:
  - name: community.general
    version: 12.4.0
  - name: community.sops
    version: 2.2.7
  - name: ansible.posix
    version: 2.1.0
roles:
  - src: xanmanning.k3s
    version: v3.6.2
  - src: mrlesmithjr.netplan
    version: v0.4.2
