---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aqua-charts.yaml
  - bjw-s-charts.yaml
  - bitnami-charts.yaml
  - cilium-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - lwolf-charts.yaml
  - metrics-server-charts.yaml
  - minecraft-server-charts.yaml
  - nfs-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - nvidia-dvp-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - stakater-charts.yaml
  - hajimari-charts.yaml
  - vector-charts.yaml
  - victoria-metrics-k8s-stack-charts.yaml
  - zalando-postgres-operator-charts.yaml
