---
# renovate: datasource=github-releases depName=traefik/traefik
traefik_version: "v3.6.9"
tianji_jwt_secret: "replace-me-with-a-random-string"
traefik_network_name: "traefik"
traefik_networks:
    - name: traefik
docker_create_networks:
    - name: traefik
