kind: Secret
amneziawg_clients_group:
    keenetic-3sad:
        public_key: ENC[AES256_GCM,data:8gLPE6c7tGy3oMDMXkBt0hkpueUKV5A5WsbXD3Qqw2lcy6SL9LNAAUj1Cmk=,iv:jAd1MHLsdLvi0vWsK6WPG10UF4y0YL+AX0qIOJ2P/0w=,tag:7dbn/f4F4HQfpNgcxb9lvg==,type:str]
        private_key: ENC[AES256_GCM,data:+ohBUCjSmPC6FpcPT1HPmQdwWjYYlMBbWZ2ywZg3fdcOqGc7Odn5O9mV3rw=,iv:GE493pAy/xSejt1XVWQLZFxW/Vm9qjUYJR4Mn0lSm/4=,tag:EevSC9hBamNVEYwxMobetg==,type:str]
        ip_suffix: ENC[AES256_GCM,data:0w==,iv:Bi11KOWuTnLUXpRGnuNJbm5qb4gMPwbYoyQYDlJqpqU=,tag:oKkpu01RPvnfdQFjKEcYjQ==,type:int]
    max-pc:
        public_key: ENC[AES256_GCM,data:cWMkORANXqs8Xf8yJVkCmm14gAfKdS8vHwfGE6EG2Aytaaa9LfdQCxB9Jc0=,iv:EE3NMDDK1x2b4crpdgLDBcnZ78BdhTphadEpjEH67Pc=,tag:A/PJsKpVVnyMgLXMfDfWcA==,type:str]
        private_key: ENC[AES256_GCM,data:nPFsMg82J0kj4keM+u6q/v5Nk/0BVEixcMsKtdECERmy5WtKvbCxsTRmOoA=,iv:q3QGp0ZHRJ0Mf2QwWbkeSRCMfJMUlOBzlyWkOd41akU=,tag:7ZaZ+H17tkO3/IoyBgC81A==,type:str]
        ip_suffix: ENC[AES256_GCM,data:iQ==,iv:f/gIO63jV0+ZBmnOl4JzTcUvYstFaV8T379a3EZQrkE=,tag:YT11ezaUdHlIKvG62pjd8Q==,type:int]
    max-phone:
        public_key: ENC[AES256_GCM,data:qbvUgIo1jg6N5acReHfsNRNiv4rM3qjgV9l38ffc1v0LL2ktaFVX42qXZDc=,iv:PRHRBa/Kpy28vVfsf6xZukzEW+UOmSwpjsWFooy2zdA=,tag:kcFEKRWNau+YHgp12li0Wg==,type:str]
        private_key: ENC[AES256_GCM,data:eA66Q9VeRHOFiCzgB5q9SOkInOlMlWyfdBzmBFYLkJqFG2YWDyw05P3hA40=,iv:7nwOZSPg5Q0vGDUidHi9tuV5SUx2EXF55DOtuFiw0hI=,tag:d/4jUpqqo/2Mq4zelepoew==,type:str]
        ip_suffix: ENC[AES256_GCM,data:Nw==,iv:T9YuWeELjPybg70gPoP4XIA+ybyYEN4yK1oyxjkVd4g=,tag:bvwmacrE3DxqDsvHUNYJLw==,type:int]
    keenetic-spb:
        public_key: ENC[AES256_GCM,data:9YioKQvUnF9XlT8XR7Ol8JWEkWLa6zu/2uwbZvyMDFTnbGx9yZHYeHm3tHo=,iv:6JwBf+FAD/HUgon0Ru066CPkDN+ehso1AGDo4tWhaAA=,tag:ew2IbdcV1JdU69P9jzNAOg==,type:str]
        private_key: ENC[AES256_GCM,data:exV1VzRgRq0zoby1xxooUHgcucvs+QqIa2dRsJCdFF9O1xpWAlshuIjL2AM=,iv:r11JsI1XRWMLMS06pViXrqjTsAov+mJM6mHhgIqEYAs=,tag:iCi8uScLo25+0IAOC5l+8Q==,type:str]
        ip_suffix: ENC[AES256_GCM,data:JA==,iv:3AnzqjKa1tf/J6zvfpnXeZiUttAHLhuzt5STtKuQxmw=,tag:8GDVDWVFh6tEJXA+ELd+FQ==,type:int]
    router-spb:
        public_key: ENC[AES256_GCM,data:uu3GqTuPCZpOAABnPCcky8JGUmv6puhwee4nqwj9oM34wwBw8q7SfkxVAqU=,iv:esXq6Y8TN6mAn5Ja4clDHED/cTf0HaM9VDLljKfaXSM=,tag:PQCANNM/F4U7CxJaYxTcKw==,type:str]
        private_key: ENC[AES256_GCM,data:ZkavdSdavBVxNAdMLjmcfT7NuByd7rAFbA4Q3EMy5oiowPXMb7seLsaGgwY=,iv:qj01yOrqqEQ6Gv8lnmY32YOJvTnje1/3qDqI+ovB/So=,tag:oCOq3vYI5qXUhDdtD0T/rg==,type:str]
        ip_suffix: ENC[AES256_GCM,data:9Q==,iv:wwhyrGcfsaMyc78vSJBZw2SZcJtz2mzilCwZAlpSA2k=,tag:wIaF6qaCrLeAgUpkRegTEQ==,type:int]
    lilo-phone:
        public_key: ENC[AES256_GCM,data:XGXXZFWIiZB4Lj7/T0PTL0HCQOBfJve4UBEAGFSv7anygOkDt4yBsSysOdI=,iv:ou+7NtMawrvHRYvJCnLvKJx84xKv/LeIwTguZaNHKvs=,tag:J+GECwBuv6FsJ/KBhqX3Wg==,type:str]
        private_key: ENC[AES256_GCM,data:yj+0HEK3PJQXIx3U4YHDp3hhBV5WH5lVs2rpMLtjzvASp3V1hwSBAAhdmt0=,iv:Z/N76Pmn8/8z6hD5RqBbHkQPLerCIsbxiMl7wtepM1I=,tag:k6BJF/W/0Vf4ogEaTx1AMA==,type:str]
        ip_suffix: ENC[AES256_GCM,data:yg==,iv:3PLsVCcqbkpKFMURZqrkXksUCpKl2Q8KE0IU4eqAq4I=,tag:qVDGnk/20E7i1RX2rgI3aA==,type:int]
    keenetic-avia42:
        public_key: ENC[AES256_GCM,data:mw5eKGPjSzklmL38m2n6oKgDGKQH1AdtxuHS0t5LY9Ad5T7HWjjn2vDRoh8=,iv:a8r9V8p84qWSRX7THgInKrm1eY312J2pANjtqgEm7x0=,tag:B9dLs/DLTB8tXrykO7R2qg==,type:str]
        private_key: ENC[AES256_GCM,data:JGsj+16fAfECWoalgJSAU+7d4aUpP/tmFqZ8wMiz556iVezLdo5uWlRV1qk=,iv:aNh47nBfgdjTfvqkc4tnodVtGgcCaXxmdRtOtOeymsI=,tag:L3WdEfck/RATXZ7A7l57OQ==,type:str]
        ip_suffix: ENC[AES256_GCM,data:6w==,iv:4iQpPHcO2+K1hy7cc1mSiKnf3/DjlP+mKwLtK5cfpSI=,tag:Ae5E8L+JVMlRc2AjdInbhw==,type:int]
    sok-phone:
        public_key: ENC[AES256_GCM,data:ecdrUKzjgIWZ/hsannXtTJV/sTyvPnAeR3fD/amy1tLF/J+HPYQLCoIi4Qc=,iv:JYWH4cmBUgbkt8z9O2V3of7iD0rg3e2ssL+hgQ0YOZY=,tag:klQoMl53niBlfctOh+LVqw==,type:str]
        private_key: ENC[AES256_GCM,data:94B+BUNE30Bubq95o0CW7r2aTIjam0WvzLUAOmXhxwMI5s2ttNGDrfYBb4Y=,iv:/K9VS9txClW1XwT3cyT1ae2S0ilq44fGNl/rm+b7Bc8=,tag:n7LB36vs7uzkZAC4/Iw9xA==,type:str]
        ip_suffix: ENC[AES256_GCM,data:qtU=,iv:kch9Fs55N5IyThSoScuYFbL1WXV2UxqVth3D+INm0WU=,tag:UD4jaZ2OuQACMmJoXYRwtw==,type:int]
    sok-pc:
        public_key: ENC[AES256_GCM,data:0MUz7N8cLk5I74LCjaKJ9M7tzLesNifbIeTGVDJxkaD0+hEmAIldAQuEN+w=,iv:u1GbJQ9LxtCJMdZ3yq0QYVz5cbIMSIroLONiYmbcRB4=,tag:FMqSt30rx0NS3RqTyh9VFw==,type:str]
        private_key: ENC[AES256_GCM,data:GQp4LTKhmthFoWg/ssayLNNOifRScY9SsR21qYFkNLsdGPRhS3cJ7FJ178Q=,iv:n2BQtigJgn8R46oW32gH13KDngexHXEU5IhL5mLVWAE=,tag:A2usGSG+ZOg0VH2WGKyJGg==,type:str]
        ip_suffix: ENC[AES256_GCM,data:hYo=,iv:9kU+o57qFrfdAeTzl4NhTpVVDphgnlkKpbGkXXKG+oM=,tag:G7U3e5zhpw9kK+kwLCsMDA==,type:int]
    sok-laptop:
        public_key: ENC[AES256_GCM,data:eg/UcCH8rQBEcaqvowOhqHX8OT9Z4Xj3zlWgf53V/0rIpWDPn8z1gDNUEe4=,iv:o28UR21CgKQ1s9rHl/7IYRISGnoktHVkXpieTddSY5o=,tag:S1NWyPlFWC+8YQjNGSZyoQ==,type:str]
        private_key: ENC[AES256_GCM,data:e+3FmHm4nh7DEPjd1Cgn2/jyPpV9hNOIHQDNhfJlAgzjBGIR71xuAzoEYhs=,iv:GuCFc+k2wl2ZlK8LSXzebsaCovvGHZyIkEuXZZAf+CQ=,tag:dwGyROJqOgxygDA+NerhcQ==,type:str]
        ip_suffix: ENC[AES256_GCM,data:uzA=,iv:cXPRj7eHV5zC0k/RKA+CjpYKF1/QG8PxlSjC5fPmRkk=,tag:JDlIj79aLiIuWk4xbJWDHQ==,type:int]
    keenetic-tkhoroshkina:
        public_key: ENC[AES256_GCM,data:Zrl+ZTzkpmj20vieTtUQ4hVwaIB4XFOSaKqSyi8m8gKqk/7eJ00sprBC8SY=,iv:dw84irXstSPwQJv8ndafPm4sHHJh82pUEuluZJXZ2hw=,tag:feVwDejGEMIQy8w/98HX4Q==,type:str]
        private_key: ENC[AES256_GCM,data:aBI+M9SkhmrYcdNPd2qPXyAhvXSZjXLL5TLo9ieZfIZ2JQU76/who4X8H+s=,iv:FElTFAKtwNOUxq+zKTzzCy6YRaycJPw9ElzGwX+MGZs=,tag:u2us4MYtEoZEJnR0EfrQow==,type:str]
        ip_suffix: ENC[AES256_GCM,data:UII=,iv:TWBuaZzbOP95b7tLw05HeXnGLLkaYKaWnuYkDxkCvfw=,tag:jAquZPsYC7KuSQJk0c38XQ==,type:int]
    tkhoroshkina-phone:
        public_key: ENC[AES256_GCM,data:bMaNEW5T8JuQ6qXaP/eGjg1SZdsWmGZk4gNS/uBafZRRDJZChYjoaOJ21s4=,iv:1Udz53ZFzITGWEiWNqXKEzM6JU67ejspcI3zVLS2VdY=,tag:rfq4fRnYFHTBNtYZOgMsbQ==,type:str]
        private_key: ENC[AES256_GCM,data:EiYVjZ8qmnqtUV98dCCmCAnQZFOrLOvTxL8RCZvwz6Fz9jdGopo9y/jYsNo=,iv:/oYt8MAYqiRZMfLANYFkFEnJj8fhPMKteH0mYtmKRC8=,tag:CDOeYpflq77td9HWVA+K5A==,type:str]
        ip_suffix: ENC[AES256_GCM,data:CwA=,iv:G1DA5XBE6Mff1nE5hwrjTNsgOIEoy02PS3ULmfAW5Mk=,tag:fhAeAWq1V8pZ+KQrzTOeSQ==,type:int]
    oxi-phone:
        public_key: ENC[AES256_GCM,data:7LjCUHrpZzNn87fZC/xembFRgewGodcL2rR97oZY9GYbcc3OHW0mvaCXijw=,iv:fgtqqs5dRam+3SV8h6twdtziLXJN4EJzNy0p66R6c2o=,tag:MujSt9GSrCgKgM6XR+OvRA==,type:str]
        private_key: ENC[AES256_GCM,data:j0gcNUjcNALYEc9po2qs4VrXhbemg00LGFWyhuu9zkK16J4tSYm1UYVqDxo=,iv:acWKcdxgElCVr2OJ5uIdf5pHKExXkHNJOG+hIgk1sf4=,tag:PoE8cLcF3S50tfRBtAMZ7g==,type:str]
        ip_suffix: ENC[AES256_GCM,data:oaA=,iv:huDWuQswrzKo64ObwYbMle3pl+cuyvrwOWu+4YAtwZ4=,tag:hJIF60i+557FhYT+NnO6tg==,type:int]
    kurbatova-val-pc:
        public_key: ENC[AES256_GCM,data:QqVcEwFbFru0H2QOEMKvucqAey8KEUNU3wL3L0SvpVVaiYGH2kPBWAjioW4=,iv:q2uP4y3BcMA5187U7xng1W8RGjlGe6SUx0ZGisSXDrM=,tag:00rRn8JiW5Hkq1RJja9eaw==,type:str]
        private_key: ENC[AES256_GCM,data:0BBWP5nmfcBGgKoNXJPHqtSX/oRMiN8NLzsOMr9GCerZt/iKwM+sK7PUK1w=,iv:7h3cU2MxcpIWtwE994lMnkFTR7TEkil1Wux55eICe3U=,tag:i3pYCti40R4s1XvcDjW9OA==,type:str]
        ip_suffix: ENC[AES256_GCM,data:n+A=,iv:p/cVMR125nWmcbWD3nhfuYs2W1/BFGJhNuVtbeJKU+U=,tag:94rqRg5Ry9tYXtZ9ZGXR4w==,type:int]
    kurbatova-val-android:
        public_key: ENC[AES256_GCM,data:+KhZUG/KE9PqcQcXRMYlgTVxucH/qL8VMNJm8dWb96dassjXMu9q7s21MbU=,iv:OC1eI//6Fjs1zLVCMOjVHb9juOQKAxkYUfrTzMv0PXw=,tag:EQUYPlqiLS+b7f6IhORT8w==,type:str]
        private_key: ENC[AES256_GCM,data:/wq/9zU1/kySLrB55UhhPrWfCF7KbK7A0Wne4I/9u8HxI+uvhvpkoOcUVN0=,iv:x9vGown15ecV627cm3kxauuDHo2JE/XVpiUwJnJvaAQ=,tag:K2SGyo16v0yLwustHq1CoQ==,type:str]
        ip_suffix: ENC[AES256_GCM,data:UG4=,iv:WDH2it8qEQK3NmJ0LP0j3MzUfbVf4ycv9d4TgnpABsE=,tag:F7kbuC11c4fO1wJTnstPOQ==,type:int]
    keenetic-3sad-openwrt-gw:
        public_key: ENC[AES256_GCM,data:DlaH0xOiUPMU/tWEtmR/7lQAEC1N0nhLUtYOS0yqGTEGe9eGCUbpEGlWV20=,iv:bf6czdA0m0jS3DOukr1rXYKko6BeqUVTni0uzXDQpkM=,tag:dqlO1Zw4qYkkm+QZOECQLw==,type:str]
        private_key: ENC[AES256_GCM,data:PfS2RL8/cwmFmtkUR5JN0kocyhEd1mmVjm7sUAIRLma3aW+UQpaQfCuwDbE=,iv:LjUT10+8o0tvceGsZF2HD+NMGbh82aABB1rZ/Rl+DzY=,tag:+GY+gNsIjkH/nG1GzY8X1Q==,type:str]
        ip_suffix: ENC[AES256_GCM,data:VkE=,iv:g8lYhOIzrvKmrybf8XrZHcFMK1btIWjmbR8HGamok4A=,tag:6P6VigXrKvdekrzsu+X3TA==,type:int]
    vps4-inbound:
        public_key: ENC[AES256_GCM,data:REjLZ9EHYFqWuLGoryS5C2nGknjS6dQZbOh2XjUN5uQ0JngUGm2XK2HXa24=,iv:GyYfwW/PUtf8/EvhwZ+V133WJ3dYvdIbGtaH/7hoMbg=,tag:cBxi0LFp1Q4s/7PtBf/PSg==,type:str]
        private_key: ENC[AES256_GCM,data:lCN/LF2JSFj9ahKtoeM8v9geNSFj1qg+MRZkHVEtVekBNPzWyx6w+4zHp90=,iv:lswTpoqsHm2EyGioM3HcoFDIacK67l51+xyT+SQ+hJY=,tag:oEQslSDDDEOHlsuiHcPHQQ==,type:str]
        preshared_key: ENC[AES256_GCM,data:dxvgZamNCApfCf3PRw4VSWyHVbzyXEy2pG7kOd9aVlAGxMYvTeVRSNMsGeo=,iv:eu/kcbwQ1MErX2WuRrO7WU+guAGq+qdTT+brl+9VilM=,tag:E0+a2Ew4dO2o/ptZLl961w==,type:str]
        endpoint: ENC[AES256_GCM,data:KdHIh3RIZhu8W0SQVXX/xeHT,iv:zApMjGUEspCqIDA5ThZSsl24I1nW8ihf4KQGtqZpS40=,tag:EGz5nk7f3IIWwzThSF6Y/A==,type:str]
        ip_suffix: ENC[AES256_GCM,data:xyjl,iv:LKZ1THlP5y2F5+XTKfHbwRgvFdQlbjXEDoEIbe3O0Es=,tag:f0N+VuTCiqKeHzYNiKY8/A==,type:int]
amneziawg_interfaces_group:
    awg0:
        #ENC[AES256_GCM,data:mqitx6iwXK1Z/NPjLu2R,iv:OHFEBrKHQDY8GRiMwAlGbnEdTRk67sfXbUOy4LK3Tv0=,tag:TQtkSuf6HkbKYihBdZdukw==,type:comment]
        mode: ENC[AES256_GCM,data:6+bfI/ek,iv:Q42dCZU6SZv0vs9ArOCjc7rNmRSatglWJ5FWoo26aCg=,tag:DH/uBN9Hab4De7yLni3KNg==,type:str]
        public_key: ENC[AES256_GCM,data:Ktlh8ihJGDkyxbxaLpht2yrZ+0OtJgSAuiYhw13epbweYdNjgnkV9ssNTA4=,iv:8oHvuah8Z0l1N2hA3st/X3f3FkEvxhz9HxBR9nY3mC4=,tag:gCh5ivnlj6cooZk36erA5w==,type:str]
        private_key: ENC[AES256_GCM,data:4A1OtL5Xlv6PldTmLm1i2XjRgCovlKNpt3s4PCgoajUSZQD/DDJqIpsbMIM=,iv:2VvtMNBtRV08VosAWy9IE6/4vwWG9bXVdHfMieQYdBg=,tag:aUuM1g2uyq68GXbOgNuFyA==,type:str]
        mtu: ENC[AES256_GCM,data:gKnlxA==,iv:W7FCAC6kzYkc2e+0gRy7Y1/+wJfUdTQPWPxAw8BZZdU=,tag:/cuGzk3+Y0qVI/lQ+p8SwA==,type:int]
        #ENC[AES256_GCM,data:2PC2QhHDp4X4kYnvkhbCHnzS9nQzlg==,iv:VbsVEXzaieXkFfWxEOtHLTgYNo5C3RAyZYscJA0A+nc=,tag:er/FSCyMPnotprs+zw2pYA==,type:comment]
        address_v4: ENC[AES256_GCM,data:khYgEL7VFyk=,iv:aPUVsFjexaVfoK2XM1bKYXW+10e+SJdF3NrUb3qvyeo=,tag:QWb/WhRpBXF5wB2s4vKNOA==,type:str]
        subnet_v4: ENC[AES256_GCM,data:lYI=,iv:Ny7dhN03oFZ/n8m0E56UfddPz1uyc7C8e4HUF/Prkvk=,tag:2CBptuIbN383HlhgpDKQ3A==,type:int]
        clients_subnet_v4: ENC[AES256_GCM,data:1lI=,iv:6/9Wxdziec+J5sEpzaoqaITq7hBL3ocCu4+hu3bY/Vs=,tag:fX1HO3bIQHWVfLHFE6jaDg==,type:int]
        address_v6: ENC[AES256_GCM,data:Owg3/wfiSD15VXUPEmMHTmQ=,iv:IhABu7DSCwtRgM/DsNAduTneHCgYn/ZY3DCfhXPd3Q8=,tag:6LRJEg5qEX+O3TCnpMWluA==,type:str]
        subnet_v6: ENC[AES256_GCM,data:EbA=,iv:RzUJdRJialrXns8K5zQkelLvyeTXES+HyoCvl+vcCBU=,tag:xoj0C5P+aeLekv25r283Ow==,type:int]
        clients_subnet_v6: ENC[AES256_GCM,data:n4wD,iv:GMe9rp+xay5wg7hZtyHKgEtpegkOJTC0953c1EqYiRw=,tag:WuZjBsjA6B1GCRZI6QCPgA==,type:int]
        #ENC[AES256_GCM,data:GXzqexbTlJ3ufPgeslgwZVj5/puL,iv:a8RJjGlFpIAR7MSzjlo4dd1ajI0iOnRBe7jsUswl54w=,tag:isVGt1n3oavke7FllkYwgA==,type:comment]
        port: ENC[AES256_GCM,data:Ek0SXtc=,iv:5J6mzdRdzuQhOpHBeZsBIIoNloxziZ44oJ56UeZA33c=,tag:HNDdjvPEw1BVxfAq/fY5wQ==,type:int]
        public_host: ENC[AES256_GCM,data:KxO56IkGHpuC1GBCeYYe5A==,iv:A/RbeXEp6dAw8hJ2twvETvXxfZ/L7vbBdLIccDrxlNE=,tag:J+CnpK97ajo3FP+PYKN6dw==,type:str]
        public_interface: null
        private_interface: ENC[AES256_GCM,data:sZjDUA==,iv:N/dPjeUMpEQ4LfCh/KM44u77+flrNydiA7BxZpqbdSI=,tag:H+mhaLaoV1NJZ1IpNXgmQQ==,type:str]
        #ENC[AES256_GCM,data:tgB3sgmadBe0i9ILulDwCEtE2kWQNz4senMHM1y/KHcZvCET467/OHd7aNR+V5k2P/OH,iv:zL9DSm+tK/fLGJ/K9taMYCZ7zmTRYwrova3tbz70ynw=,tag:IRwCZesE10yOj8rHZHbMzw==,type:comment]
        jc: ENC[AES256_GCM,data:1g==,iv:kDwSZEPnMfWdW+MimBQbGNBIgLjb4bCXxFsKBiszvec=,tag:BPMxA3/H9az0TvhGHyVF4g==,type:int]
        jmin: ENC[AES256_GCM,data:zzsv,iv:OoDiJbjYo0qDUmvXzzY5whCS4MlTZMqi5XGjCQLeqds=,tag:SXoylmuaW22bEC4SMGhhBg==,type:int]
        jmax: ENC[AES256_GCM,data:Si5iPQ==,iv:E/r9XSlhsI3VkLgR48i/6WpLG1qicGWoGh6+78BMMao=,tag:sk/Iz3ctuK8tx71FJt00XA==,type:int]
        s1: ENC[AES256_GCM,data:niM=,iv:fi9UoKJs5kkvF60gphdRTHvhN8Ns8tqzqlJiBd0mGd8=,tag:K132MSJn1rOkd67/3W/aiw==,type:int]
        s2: ENC[AES256_GCM,data:rBE=,iv:aSdYVk8bj2Nc+yhAdUlKE6E/xe56sgosEnPvc29Afo0=,tag:dJ9fYZqc0MpaxrxajxDvoA==,type:int]
        h1: ENC[AES256_GCM,data:SUDVKysupef0,iv:N/7/7a8VkfY70hmx2ukrOnlfEz6s1uws4+slk79S5jk=,tag:oP848v+ZVKRwOLtjTl9nvw==,type:int]
        h2: ENC[AES256_GCM,data:N2aSoSzNK1y/,iv:KeieN0r0Ag+4Qe8/KJmOhaUfNmkKWmgHpJXxNAKiuFA=,tag:Dce2zkVhAkcSDUwH3MGUag==,type:int]
        h3: ENC[AES256_GCM,data:JDjC+e3W9cZT6g==,iv:0fJZWVf6YRNaYBKqihj5oawUECmZlormEJ+slrNhtXg=,tag:Lq1aOyyjP9ueEkdKTifOvg==,type:int]
        h4: ENC[AES256_GCM,data:ghiF4nK9oXPE,iv:LF+hcP07nmarbpG/3yGeXMscAFvFqvMoTeOv0KrjuHU=,tag:XcChUUSrYvjj04gkUbl8eg==,type:int]
        peers:
            - ENC[AES256_GCM,data:r57YODE/kv2/ZRSAKg==,iv:jn+duP7/cUJ4WVvuv0V0C+3lSPxS7ZMxhkehFgYqvto=,tag:VCCWmvLUSLRdJRG1PA/2Cg==,type:str]
            - ENC[AES256_GCM,data:e8AZkaNa,iv:rNw3DArstGXzHxNHRidDlDAV99CiN8IvfWgmkMs+eGk=,tag:MAYqgOdv+9lMz5zW2DgO9Q==,type:str]
            - ENC[AES256_GCM,data:meZkBHkue5RH,iv:brM4Oyi9pY0/xjdk9sJ6+dxXbzp+KD7RCY32VHtCOfI=,tag:rXzHgS5nkoho7QiRUYC/Ww==,type:str]
            - ENC[AES256_GCM,data:Z9YAPahn5IDL43R+,iv:iuVjX/d1DAQjjoDsea+SGG8xgxKXNPPpnxLrIu3hS3M=,tag:Qe0fbfJ3L6JodVHPgO62jQ==,type:str]
            - ENC[AES256_GCM,data:TgI3B9aql2lGLg==,iv:yOXkwWdr0ziIej7bGHzs6U1bTPo3ukWbQ4AwvjSp1Q0=,tag:PwfTuwN0438StJdzJ1+YbA==,type:str]
            - ENC[AES256_GCM,data:6VV4PpVp67bFIg==,iv:4swvojzNBhz7c8RAlW9WzR8GuD78UnGT20ngroYyOpc=,tag:/AIiCRbxvaHtujUTSVZU0g==,type:str]
            - ENC[AES256_GCM,data:FU+bV2opKOGhG1C8FnyZ,iv:9yYT+/bnPG++kpbaxgTp6mT/ZJfmq08smUKZOtDM55M=,tag:6TFdNHJ3s72Z3YlaV90LIg==,type:str]
            - ENC[AES256_GCM,data:bXMNnknglIkF,iv:vwboz91tCy75IOALHkzAII1IO/rM4SwFtwN24O4joYQ=,tag:ZRi25fXzzlfwoHBTlXl4wA==,type:str]
            - ENC[AES256_GCM,data:y1qcCFOK,iv:HgN8uoFTukOEOVUarwtRCl299rO9LqNhSh8sJMKDfQw=,tag:Oab/3rUshO01b/vLDFyRqQ==,type:str]
            - ENC[AES256_GCM,data:OrTajy7faSfwig==,iv:hQYOR3FWi5Vo5Y3z0Ex6HyWMJRvgzvfasL/zQ8zovIM=,tag:Vi5jYUPWUrn74FJxqz/8Sw==,type:str]
            - ENC[AES256_GCM,data:heDD2/GXq2jLIr6IqCiEDXzRVR56,iv:1+D4zFYgcYjwgPyaUZjpCMEP2v0KBB4ly/rXfHST5YY=,tag:n3Cn7Q8caVrap0gbXC4cRw==,type:str]
            - ENC[AES256_GCM,data:dPnBQ9sDHAV3JIT4xSxa6Ogw,iv:diFx1Y0fABZLJODeSnPTVMknMeqEolLWTootn5QKT54=,tag:ZDqyjviDkm9eTeY1xMn/hQ==,type:str]
            - ENC[AES256_GCM,data:bfc6sLgAOZCU,iv:rQyXg12cGmG7tbaiQLguMeYvj9ORIH0dPExboURTh+w=,tag:Z/yvhI5/plMn6izf23/6Ig==,type:str]
            - ENC[AES256_GCM,data:YSmxO1GaDuMbVLwKb/WOsA==,iv:jqXKEw4CccJiI79dN7rzwTlm47Zb3N74oj4TEOn4A5U=,tag:yZ0ljvt2Susd1xydPPAYYg==,type:str]
            - ENC[AES256_GCM,data:mXvUbATBDVm2AxJTuX7Spg5ZjGKl,iv:90EdvJdTRJPTKisygRtBTPARr1G8NKr0Hku0ELqvwnY=,tag:FZjYUUeqGdgNkzm0H2FRSA==,type:str]
            - ENC[AES256_GCM,data:2pGndKYbl6wMlrnxb/faa5rlZWltisby,iv:V0iZiy4IUJ0YiXnvz+vjIQj+jic+iUe4uUBtMnZxIVs=,tag:QOkWlTN1zf5bo81nA8LvPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVoraGdURCs2U1ZjMFY5
            c2pyWFBzS0dWemhPT1pSVk1Cd01xOUZocXk0CnYxeTNqZHVzYk9FNS9MSDFoazUz
            ZkQrczhxWEx4dE5WblIwdG9IWGpKOUUKLS0tIEdEMXZPa1gybStDR1p0dFEyNnpF
            Y284bkQ5Y09yN3pyRDVkWHk4TVFhZk0KsuXMnTcefEaBnZrA2lUIB6Q7Nd/ASndZ
            OufZVVJTOADqMzcmicsz03ozIrTPcYbHE8Q5n2oKIJ6XLenwrcrDFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T19:20:05Z"
    mac: ENC[AES256_GCM,data:IEmQ2jUH9qEdxDEry+cQbro61XpS/3DwzmvMMAF/CNSxioHRBTL/2NxtkLmeybxPBwxzmbgXqJfol6bmAMNkbUjXE7u4LhNs38x9cwsXgngsa876hr5YA2RJbIE0vq0nK7kvM/f0Bgj0/kHiBjgNrYUjXmcLk+T8ECroBOyHXIQ=,iv:B1TPI+1DwFJ0tmWUNTREXfBaAzR+kmPU/nRVPw0lRj8=,tag:u498jskVE3/hDYb6qpJjzQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
