# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP}-config
  labels:
    app.kubernetes.io/name: ${APP}
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    gateway: true
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: sm
    iconStyle: theme
    color: teal
    disableIndexing: true
    layout:
      Media:
        style: row
        columns: 4
      Home:
        style: row
        columns: 4
      Personal Services: {}
      Tools: {}
      Middleware: {}
      Maintenance: {}
    language: ru
    providers:
      openweathermap: ${SECRET_HOMEPAGE_OPENWEATHERMAP_API_KEY}
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Media: []
    - Personal Services: []
    - Home: []
    - Tools: []
    - Middleware: []
    - Maintenance: []
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        showSearchSuggestions: true
        focus: false
        target: _self
    - openweathermap:
        provider: openweathermap
        cache: 15
        units: metric
  docker.yaml: ""
