---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Saratov"
  CLUSTER_NAME: "cluster01"
  CLUSTER_ID: "1"
  CONTROL_PLANE_ENDPOINT: "10.75.40.21"
  GATEWAY_IP: 10.75.0.1
  ROUTER_IP: 192.168.40.1
  PVE_HOST_IP: 192.168.41.5
  NETWORK_K8S_CLUSTER_CIDR: 172.22.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 172.24.0.0/16
  NETWORK_MANAGEMENT_CIDR: 10.0.0.0/8
  NETWORK_BGP_SVC_RANGE: 10.5.0.0/24
  SMTP_EMAIL: notify@cubly.ru
  SMTP_HOST: smtp.mailgun.org
  SVC_NGINX_ADDR: 10.5.0.100
  SVC_K8S_GATEWAY_ADDR: 10.5.0.101
  SVC_DATABASE_ADDR: 10.5.0.102
  SVC_FRIGATE_ADDR: 10.5.0.103
  SVC_HOME_ASSISTANT_ADDR: 10.5.0.104
  SVC_MQTT_ADDR: 10.5.0.105
  SVC_VECTOR_AGGREGATOR_ADDR: 10.5.0.106
  SVC_PLEX_ADDR: 10.5.0.107
  SVC_JELLYFIN_ADDR: 10.5.0.108
  SVC_OWNCAST_ADDR: 10.5.0.109
  SVC_SYNCTHING_ADDR: 10.5.0.110
  SVC_ISPY_ADDR: 10.5.0.111
  SVC_MINECRAFT_ADDR: 10.5.0.112
  NFS_PROXMOX_ADDR: 10.75.40.1
  NFS_PROXMOX_POD_DATA: /tank/pod-data
  NFS_PROXMOX_MEDIA: /tank/media
  NFS_PROXMOX_CCTV: /tank/media/03_cctv
  NFS_PROXMOX_CCTV_ISPY: /tank/media/03_cctv_ispy
  NFS_PROXMOX_POSTGRES: /tank/postgres
  NFS_BACKUP_ADDR: 192.168.102.102
  NFS_BACKUP_SNAPSHOTS: "/backup/kopia/cluster0"
  CLUSTER_CLOUDFLARE_TUNNEL_ID: 50e0afee-afa0-4655-a455-07217586696f
