---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-services
  - ./sftpgo/ks.yaml
  - ./syncthing/ks.yaml
  - ./homepage/ks.yaml
  - ./kopia/ks.yaml
  - ./minio/ks.yaml
  - ./paperless/ks.yaml
  - ./scanservjs/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./firefly-iii/ks.yaml
