---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-services
  - sftpgo
  - syncthing
  - hajimari
  - gluetun
  - kopia
  # - minecraft-server
  - minio
  - theme-park
  - tianji
