---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-snapshotter
  # - ext-postgres-operator
  - kube-prometheus-stack
  # - kyverno
  - zalando
  - victoria-metrics
