kind: Secret
ansible_host: ENC[AES256_GCM,data:K1il58YfOANy3t44,iv:lPEffTbEA9+cdT2zkPJiKk2tqHiASLiDdV3eNmRlH4k=,tag:52LbWBprWCLAfpeLUpXmiA==,type:str]
ansible_user: ENC[AES256_GCM,data:jxd8ug==,iv:nRUyPHIebzT5igyisst3VPEXwuTQvEKNRZKFng87uAU=,tag:GQ05Fl/YKxDt+o9i4nIKBQ==,type:str]
#ENC[AES256_GCM,data:2OsMupu+kFn4UnX1993AJox2olCgwviaz9EmQs2SQ8iQgKf6apm1yjhRsMfwfg==,iv:djXfjzoo32wU9yMAHd8di92LKGfccgjWSXw6HLRY2A8=,tag:uZ2r5VBU66mWjPdmkQQ5FQ==,type:comment]
scrutiny_collector_api_endpoint: ENC[AES256_GCM,data:ckVXjyHZNjDUC3hfima7RvwqLKTc1GoyQDZPeK/IQhYIYk9rpzwMqlotF/ii3h8PsFY1hxvsDL47D3aJak7B1H0nzFU=,iv:dXtjxBH3q0EFORPPMOXrGt9pzP5iMFDdg0vCXXQ+rXE=,tag:5L55i/wc0okIcIqy5B3qxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVoraGdURCs2U1ZjMFY5
            c2pyWFBzS0dWemhPT1pSVk1Cd01xOUZocXk0CnYxeTNqZHVzYk9FNS9MSDFoazUz
            ZkQrczhxWEx4dE5WblIwdG9IWGpKOUUKLS0tIEdEMXZPa1gybStDR1p0dFEyNnpF
            Y284bkQ5Y09yN3pyRDVkWHk4TVFhZk0KsuXMnTcefEaBnZrA2lUIB6Q7Nd/ASndZ
            OufZVVJTOADqMzcmicsz03ozIrTPcYbHE8Q5n2oKIJ6XLenwrcrDFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T17:56:30Z"
    mac: ENC[AES256_GCM,data:oYpdm3I/uN/L05XNtcGPgx5sG0BHD94eYvFW/Rlt+/eaOoIKSo0PNN7Pid0nDLBE101lzqdZD+nLhuDAVJum0jZIgaEhBc+WHDcFlb25XO5DebNhW7hOEWyRLgAmythDbXZAwzF8HOVBugdBq/ZWURsLkQDtdpZoizhwG/6dH/Q=,iv:xJFgy3Hcdos0D3ZOd9gXRmZei8sT+pq4lsxbVo81G/E=,tag:tPMn4t2DSeTf/GWP9470Qg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
