kind: Secret
ansible_host: ENC[AES256_GCM,data:FxEyC4FDFjz9zAk=,iv:mBrFkhNY6RZ/KetXtlb2/Ydt+xCyBqLZYiwP8ipQ8P8=,tag:MaSZZI0YLJeB5hzoWh6zHQ==,type:str]
ansible_user: ENC[AES256_GCM,data:jxd8ug==,iv:nRUyPHIebzT5igyisst3VPEXwuTQvEKNRZKFng87uAU=,tag:GQ05Fl/YKxDt+o9i4nIKBQ==,type:str]
iperf3_client_hostname: ENC[AES256_GCM,data:1RdBnKLO7NiU9WxxOTcrM41N,iv:1C5qCG3NTKvOvpZrf6U2ZoRluxEGcTqFnBZmrh0Kd/E=,tag:4rH7brt0y4Igu+Mv7PukrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVoraGdURCs2U1ZjMFY5
            c2pyWFBzS0dWemhPT1pSVk1Cd01xOUZocXk0CnYxeTNqZHVzYk9FNS9MSDFoazUz
            ZkQrczhxWEx4dE5WblIwdG9IWGpKOUUKLS0tIEdEMXZPa1gybStDR1p0dFEyNnpF
            Y284bkQ5Y09yN3pyRDVkWHk4TVFhZk0KsuXMnTcefEaBnZrA2lUIB6Q7Nd/ASndZ
            OufZVVJTOADqMzcmicsz03ozIrTPcYbHE8Q5n2oKIJ6XLenwrcrDFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T10:04:48Z"
    mac: ENC[AES256_GCM,data:Zmo0kfytAuGNgnuSwFACXLO9XssNI4txXKutxh0r1b7ZMGflheWCahyQeCKBny/wYCM2om2Uw6NCx3oLXEzytLjwyclufke6W7jDjvdZxJJpAosdjBmWYKs59sVJFWXm/zdUZaCB/k0up77/3xce+bPnc2muM8KIW4vkKe/3aVI=,iv:D+purGF+pVlJGdq60VHZBm9HCVkCm9u61OyGvMl3hOU=,tag:Sz4hcfJZkpfr+M4BmGoY2Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
