---
- import_tasks: docker.yaml
  tags:
    - docker
  when: (traefik_enabled | default(false)) or (gatus_config is defined) or (vpn_tgproxy_enabled | default(false)) or (vpn_xui_enabled | default(false))

- import_tasks: traefik.yaml
  tags:
    - traefik
  when: traefik_enabled | default(false)

- import_tasks: gatus.yaml
  tags:
    - gatus
  when: gatus_config is defined
